name: Deploy To EKS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: nodejs-app
  CLUSTER_NAME: demo-eks

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Check AWS Identity
      run: |
        aws sts get-caller-identity

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker Image
      run: |
        docker build -t $ECR_REPOSITORY ./app

    - name: Tag Docker Image
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        docker tag $ECR_REPOSITORY:latest \
        $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest

    - name: Push Docker Image
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        docker push \
        $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig \
        --region $AWS_REGION \
        --name $CLUSTER_NAME

    - name: Show kubeconfig context
      run: |
       kubectl config current-context
    
    - name: Verify EKS Access
      run: |
        kubectl get nodes

    - name: Deploy Application
      run: |
        kubectl apply -f kubernetes/